version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./tensorflow_project:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  tf_serving:
    build:
      context: ./models
      dockerfile: Dockerfile
    image: tf_serving
    volumes:
      - ./models/my_model/1:/models/my_model/1
    ports:
      - "8501:8501"

volumes:
  postgres_data:
